---
- name: Check if WordPress is already installed.
  command: >
    {{ wp_cli_bin_path }} core is-installed
    --allow-root
    chdir={{ beet_root }}
  register: wp_site_installed
  failed_when: false
  changed_when: false

- name: Download WordPress core.
  command: >
    {{ wp_cli_bin_path }} core download
    --path={{ beet_root }}
    --allow-root
    creates={{ beet_root }}/wp-content/index.php

- name: Generate WordPress wp-config.php file.
  command: >
    {{ wp_cli_bin_path }} core config
    --dbname={{ beet_mysql_database }}
    --dbuser={{ beet_mysql_user }}
    --dbpass={{ beet_mysql_password }}
    --allow-root
    chdir={{ beet_root }}
    creates={{ beet_root }}/wp-config.php

- name: Create the WordPress tables in the database.
  command: >
    {{ wp_cli_bin_path }} core install
    --url={{ beet_domain }}
    --title={{ beet_site_name }}
    --admin_user={{ wp_account_name }}
    --admin_password={{ wp_account_pass }}
    --admin_email={{ wp_account_email }}
    --allow-root
    chdir={{ beet_root }}
  when: wp_site_installed.rc != 0
