---
beet_domain: "wordpress.local"
beet_root: "{{ beet_base }}/docroot"
role_path: "{{ beet_home }}/provisioning/ansible/roles/beetboxvm.wordpress"

beet_project: wordpress
wp_download_core: yes
wp_install_site: yes
wp_account_name: admin
wp_account_pass: admin
wp_account_email: "admin@beetbox.local"
